name: hello-gitops-cicd

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: hello-gitops

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # scan do codigo fonte e dependencias
      - name: Scan de segurança (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: "0"
          format: table

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: lpgin ecr
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e push da imagem
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          TAG=${GITHUB_SHA::7}
          IMAGE=$REGISTRY/$ECR_REPOSITORY
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      # scan artefato SO base (apt/debian)
      - name: Scan de segurança da imagem (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}:${{ env.TAG }}
          severity: CRITICAL,HIGH
          exit-code: "1"
          format: table